-- Create partitions for accounts_current
CREATE TABLE accounts_current_p0 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE accounts_current_p1 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE accounts_current_p2 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE accounts_current_p3 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE accounts_current_p4 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE accounts_current_p5 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE accounts_current_p6 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE accounts_current_p7 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE accounts_current_p8 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE accounts_current_p9 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE accounts_current_p10 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE accounts_current_p11 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE accounts_current_p12 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE accounts_current_p13 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE accounts_current_p14 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE accounts_current_p15 PARTITION OF accounts_current FOR VALUES WITH (MODULUS 16, REMAINDER 15);

-- Create partitions for storage_current
CREATE TABLE storage_current_p0 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE storage_current_p1 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE storage_current_p2 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE storage_current_p3 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE storage_current_p4 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE storage_current_p5 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE storage_current_p6 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE storage_current_p7 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE storage_current_p8 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE storage_current_p9 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE storage_current_p10 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE storage_current_p11 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE storage_current_p12 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE storage_current_p13 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE storage_current_p14 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE storage_current_p15 PARTITION OF storage_current FOR VALUES WITH (MODULUS 16, REMAINDER 15); 