-- Create BRIN indexes on last_access_block for accounts_current partitions
-- BRIN indexes are more efficient for time-series data like block numbers
CREATE INDEX CONCURRENTLY idx_accounts_current_p0_last_access_block ON accounts_current_p0 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p1_last_access_block ON accounts_current_p1 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p2_last_access_block ON accounts_current_p2 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p3_last_access_block ON accounts_current_p3 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p4_last_access_block ON accounts_current_p4 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p5_last_access_block ON accounts_current_p5 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p6_last_access_block ON accounts_current_p6 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p7_last_access_block ON accounts_current_p7 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p8_last_access_block ON accounts_current_p8 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p9_last_access_block ON accounts_current_p9 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p10_last_access_block ON accounts_current_p10 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p11_last_access_block ON accounts_current_p11 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p12_last_access_block ON accounts_current_p12 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p13_last_access_block ON accounts_current_p13 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p14_last_access_block ON accounts_current_p14 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_accounts_current_p15_last_access_block ON accounts_current_p15 USING BRIN (last_access_block);

-- Create BRIN indexes on last_access_block for storage_current partitions
CREATE INDEX CONCURRENTLY idx_storage_current_p0_last_access_block ON storage_current_p0 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p1_last_access_block ON storage_current_p1 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p2_last_access_block ON storage_current_p2 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p3_last_access_block ON storage_current_p3 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p4_last_access_block ON storage_current_p4 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p5_last_access_block ON storage_current_p5 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p6_last_access_block ON storage_current_p6 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p7_last_access_block ON storage_current_p7 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p8_last_access_block ON storage_current_p8 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p9_last_access_block ON storage_current_p9 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p10_last_access_block ON storage_current_p10 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p11_last_access_block ON storage_current_p11 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p12_last_access_block ON storage_current_p12 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p13_last_access_block ON storage_current_p13 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p14_last_access_block ON storage_current_p14 USING BRIN (last_access_block);
CREATE INDEX CONCURRENTLY idx_storage_current_p15_last_access_block ON storage_current_p15 USING BRIN (last_access_block);