-- Drop existing BRIN indexes on last_access_block for accounts_current partitions
DROP INDEX IF EXISTS idx_accounts_current_p0_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p1_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p2_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p3_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p4_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p5_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p6_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p7_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p8_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p9_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p10_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p11_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p12_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p13_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p14_last_access_block;
DROP INDEX IF EXISTS idx_accounts_current_p15_last_access_block;

-- Drop existing BRIN indexes on last_access_block for storage_current partitions
DROP INDEX IF EXISTS idx_storage_current_p0_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p1_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p2_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p3_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p4_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p5_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p6_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p7_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p8_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p9_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p10_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p11_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p12_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p13_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p14_last_access_block;
DROP INDEX IF EXISTS idx_storage_current_p15_last_access_block;

-- Create new B-tree indexes on last_access_block for accounts_current partitions
CREATE INDEX idx_accounts_current_p0_last_access_block ON accounts_current_p0 (last_access_block);
CREATE INDEX idx_accounts_current_p1_last_access_block ON accounts_current_p1 (last_access_block);
CREATE INDEX idx_accounts_current_p2_last_access_block ON accounts_current_p2 (last_access_block);
CREATE INDEX idx_accounts_current_p3_last_access_block ON accounts_current_p3 (last_access_block);
CREATE INDEX idx_accounts_current_p4_last_access_block ON accounts_current_p4 (last_access_block);
CREATE INDEX idx_accounts_current_p5_last_access_block ON accounts_current_p5 (last_access_block);
CREATE INDEX idx_accounts_current_p6_last_access_block ON accounts_current_p6 (last_access_block);
CREATE INDEX idx_accounts_current_p7_last_access_block ON accounts_current_p7 (last_access_block);
CREATE INDEX idx_accounts_current_p8_last_access_block ON accounts_current_p8 (last_access_block);
CREATE INDEX idx_accounts_current_p9_last_access_block ON accounts_current_p9 (last_access_block);
CREATE INDEX idx_accounts_current_p10_last_access_block ON accounts_current_p10 (last_access_block);
CREATE INDEX idx_accounts_current_p11_last_access_block ON accounts_current_p11 (last_access_block);
CREATE INDEX idx_accounts_current_p12_last_access_block ON accounts_current_p12 (last_access_block);
CREATE INDEX idx_accounts_current_p13_last_access_block ON accounts_current_p13 (last_access_block);
CREATE INDEX idx_accounts_current_p14_last_access_block ON accounts_current_p14 (last_access_block);
CREATE INDEX idx_accounts_current_p15_last_access_block ON accounts_current_p15 (last_access_block);

-- Create new B-tree indexes on last_access_block for storage_current partitions
CREATE INDEX idx_storage_current_p0_last_access_block ON storage_current_p0 (last_access_block);
CREATE INDEX idx_storage_current_p1_last_access_block ON storage_current_p1 (last_access_block);
CREATE INDEX idx_storage_current_p2_last_access_block ON storage_current_p2 (last_access_block);
CREATE INDEX idx_storage_current_p3_last_access_block ON storage_current_p3 (last_access_block);
CREATE INDEX idx_storage_current_p4_last_access_block ON storage_current_p4 (last_access_block);
CREATE INDEX idx_storage_current_p5_last_access_block ON storage_current_p5 (last_access_block);
CREATE INDEX idx_storage_current_p6_last_access_block ON storage_current_p6 (last_access_block);
CREATE INDEX idx_storage_current_p7_last_access_block ON storage_current_p7 (last_access_block);
CREATE INDEX idx_storage_current_p8_last_access_block ON storage_current_p8 (last_access_block);
CREATE INDEX idx_storage_current_p9_last_access_block ON storage_current_p9 (last_access_block);
CREATE INDEX idx_storage_current_p10_last_access_block ON storage_current_p10 (last_access_block);
CREATE INDEX idx_storage_current_p11_last_access_block ON storage_current_p11 (last_access_block);
CREATE INDEX idx_storage_current_p12_last_access_block ON storage_current_p12 (last_access_block);
CREATE INDEX idx_storage_current_p13_last_access_block ON storage_current_p13 (last_access_block);
CREATE INDEX idx_storage_current_p14_last_access_block ON storage_current_p14 (last_access_block);
CREATE INDEX idx_storage_current_p15_last_access_block ON storage_current_p15 (last_access_block);